version: '3.1'

services:
  api-server:
    build: .
    ports:
      - 5002:5002
    env_file:
      - .env
    networks:
      - banking-system
    depends_on:
      - mongo
  mongo:
    container_name: banking_db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - banking-system
    volumes:
      - mongo-data:/data/db
networks:
  banking-system:
    driver: bridge
volumes:
  mongo-data:
    driver: local